vector_search:  vector_search.o
	g++	-std=c++11	-Wall	-Werror	vector_search.o -o	vector_search
vector_search.o : vector_search.cc
	g++	-std=c++11	-Wall	-Werror	-c	vector_search.cc
clean:
	rm  *.o	vector_search
 